# Generated by Django 4.1.5 on 2023-01-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpieaceposes',
            name='health',
            field=models.CharField(default='100', max_length=5),
        ),
    ]
