# Generated by Django 4.1.5 on 2023-01-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_userpieaceposes_health'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpieaceposes',
            name='health',
            field=models.CharField(default='100.0', max_length=50),
        ),
    ]
